import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';

export default function Header() {
  const [open, setOpen] = useState(false);

  return (
    <header className="fixed top-0 left-0 right-0">
      <Head>
        <title>Elaborate Walks - Live Streaming</title>
        <meta
          name="description"
          content="Generated by elaborate Walks - Live Streaming"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex bg-[#7B7B7B] px-4 py-2 items-center">
        {/* mobile Menu Starts */}
        <div
          className={`md:hidden absolute top-0 left-0 h-screen w-screen z-50 bg-[#7B7B7B] px-4 transform ${
            open ? '-translate-x-0' : '-translate-x-full'
          } transition-transform duration-300 ease-in-out  `}
        >
          <div
            className="flex items-center justify-center mx-auto mt-5 bg-[#7B7B7B]"
            onClick={() => setOpen(false)}
          >
            {' '}
            {/*logo container*/}
            <Link
              href="/"
              className="text-xl font-semibold flex justify-center items-center text-white"
            >
              Elaborate Walks
            </Link>
          </div>
          <div className="flex flex-col gap-10 text-white text-base mt-16">
            <div onClick={() => setOpen(false)}>
              <Link href="#">Index</Link>
            </div>
            <div onClick={() => setOpen(false)}>
              <Link href="#">About</Link>
            </div>
            <div onClick={() => setOpen(false)}>
              <Link href="#">Stories</Link>
            </div>
            <div onClick={() => setOpen(false)}>
              <Link href="#">All Rights Reserved</Link>
            </div>
          </div>
        </div>
        {/* mobile Menu End*/}

        {/* Main Menu Starts*/}
        <div className="w-full flex justify-between items-center">
          <div className="hidden md:flex justify-between w-3/12 text-sm leading-[14px] font-normal text-white">
            <Link href="#">Index</Link>
            <Link href="#">About</Link>
          </div>
          <div
            className="z-50 flex relative w-8 h-6 flex-col justify-between items-center md:hidden"
            onClick={() => {
              setOpen(!open);
            }}
          >
            {/* hamburger button */}
            <span
              className={`h-[3px] w-full bg-white rounded-lg transform transition duration-300 ease-in-out ${
                open ? 'rotate-45 translate-y-2.5 bg-white' : ''
              }`}
            />
            <span
              className={`h-[3px] w-full bg-white rounded-lg transform transition duration-300 ease-in-out ${
                open ? '-rotate-45 -translate-y-2.5 bg-white' : ''
              }`}
            />
          </div>

          <div className="md:w-6/12 w-8/12 mx-auto flex items-center md:justify-center justify-end">
            <Link href="/" className="text-2xl font-semibold text-white">
              Elaborate Walks
            </Link>
          </div>

          <div className="hidden md:flex justify-between w-3/12 text-sm leading-[14px] font-normal text-white">
            <Link href="#">Stories</Link>
            <Link href="#">All Rights Reserved</Link>
          </div>
        </div>
        {/* mobile Menu End*/}
      </nav>

      <div className="overflow-x-hidden w-screen border-y border-black bg-white">
        <div className="whitespace-nowrap">
          <span className="text-xs leading-[16px] font-normal text-black mx-4 uppercase">
            Connecting the world wide community of golf enthusiast through
            interactive live internet experiences
          </span>
          <span className="text-xs leading-[16px] font-normal text-red-600 mx-4 uppercase">
            LIVE
          </span>
        </div>
      </div>
    </header>
  );
}
