import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import LiveScroll from './liveScroll';
import Logo from '../public/logo.svg';
import Home from '../public/images/home.svg';
import About from '../public/images/about.svg';
import Feature from '../public/images/feature.svg';
import Copyright from '../public/images/copyright.svg';
import Home_yellow from '../public/images/home-yellow.svg';
import About_yellow from '../public/images/about-yellow.svg';
import Feature_yellow from '../public/images/feature-yellow.svg';
import Copyright_yellow from '../public/images/copyright-yellow.svg';

import { useRouter } from 'next/router';

export default function Header({url}) {
  const [open, setOpen] = useState(false);
  const router = useRouter();
  var link = router.query['streaming'];

  return (
    <header className="fixed top-0 left-0 right-0 z-50">
      <Head>
        <title>Elaborate Walks - Live Streaming</title>
        <meta
          name="description"
          content="Generated by elaborate Walks - Live Streaming"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex  items-center">        
        {/* Main Menu Starts*/}
        <div className="w-full flex flex-col justify-between items-center">
      <ul className={`grid md:grid-cols-4 grid-cols-2 justify-between w-full px-4 pt-2 ${link == url ? 'bg-[#F2F2F2]' : 'bg-transparent'}`}>
            <li className='text-left md:block hidden'>
              <Link
                href="/"
                className={`HelveticaNowText text-xs leading-[14px] font-medium inline-flex max-w-[140px] max-h-[35px] w-full h-full`}>
                {router.pathname == '/' ? (
                  <Image src={Home_yellow} alt="white-logo" width={165} height={40} ></Image>) :
                  (
                    <Image src={Home} alt="logo" width={165} height={40} ></Image>
                  )}
              </Link>
            </li>
            <li className='text-left'>
              <Link href="/about" className={`HelveticaNowText text-xs leading-[14px] font-medium inline-flex max-w-[50px] max-h-[35px] w-full h-full`}>
              {router.pathname == '/about' ? (
                  <Image src={About_yellow} alt="white-logo" width={165} height={40} ></Image>) :
                  (
                    <Image src={About} alt="logo" width={165} height={40} ></Image>
                  )}
              </Link>
            </li>
            <li className='text-right'>
              <Link href="/stories" className={`HelveticaNowText text-xs leading-[14px] font-medium inline-flex max-w-[60px] max-h-[35px] w-full h-full`}>
              {router.pathname == '/stories' ? (
                  <Image src={Feature_yellow} alt="white-logo" width={165} height={40} ></Image>) :
                  (
                    <Image src={Feature} alt="logo" width={165} height={40} ></Image>
                  )}
              </Link>
            </li>
            <li className='text-right md:block hidden'>
              <Link href="" className={`HelveticaNowText text-xs leading-[14px] font-medium inline-flex max-w-[140px] max-h-[35px] w-full h-full`}>
              {router.pathname == '' ? (
                  <Image src={Copyright_yellow} alt="white-logo" width={165} height={40} ></Image>) :
                  (
                    <Image src={Copyright} alt="logo" width={165} height={40} ></Image>
                  )}
              </Link>
            </li>
          </ul>
          <div className="bg-transparent w-full px-4 py-3 flex flex-row justify-between items-center">            
            <div className="md:w-full mx-auto flex items-center md:justify-center justify-end">
              <Link href="/" className="justify-center flex">
                <Image src={Logo} alt="" className="w-full" />
              </Link>
            </div>
          </div>
        </div>
        {/* mobile Menu End*/}
      </nav>

      {/* <LiveScroll Custom_bg="bg-white" Text_color="text-black" /> */}
    </header>
  );
}
